locks-review-team: neokeit
team-leads-team: neokeit
action-review-team: neokeit

rules:
  - name: Aprobaciones
    condition: .*
    check_type: diff
    all_distinct:
      - min_approvals: 1
        teams:
          - apolo-access
      - min_approvals: 1
        teams:
          - admins
      - min_approvals: 1
        teams:
          - apolo-verne
